[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "recruit_restaurant_visitor_forecasting"
version = "0.0.1"
description = "Predict how many future visitors a restaurant will receive"
authors = [
  { name = "Kozlova Tatsiana" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.13.0"
dependencies = [
    "numba >= 0.61",
    "llvmlite >= 0.44",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.2",
    "tqdm>=4.67.3",
    "pandas>=2.3.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "ipython>=9.11.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "scikit-learn>=1.8.0",
    "joblib>=1.5.3",
    "mlflow>=3.10.1",
    "mlflow-skinny>=3.10.1",
    "shap>=0.50.0",
    "optuna>=4.8.0",
    "lightgbm>=4.6.0",
    "plotly>=6.6.0",
    "notebook>=7.5.5",
    "ipywidgets>=8.1.8",
    "pingouin>=0.6.1",
]


[tool.ruff]
line-length = 99
src = ["recruit_restaurant_visitor_forecasting"]
include = ["pyproject.toml", "recruit_restaurant_visitor_forecasting/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["recruit_restaurant_visitor_forecasting"]
force-sort-within-sections = true

